### ISSUE TITLE
What batch_size did you use?

### ISSUE THREAD

**Issue by dev-kodeplus** [faizan1234567/Brain-Tumors-Segmentation#7]
Hello,

You didn't mention batch size in the ReadMe so I assume you're using batch size as 1. Is that correct?

Thanks!

**Comment by faizan1234567** [comment]
@dev-kodeplus yes, the batch size 1 is used.

**Comment by usamaahme** [comment]
there is not a perfect clear guide how to run this project? will you explain

**Comment by faizan1234567** [comment]
@usamaahme Please refer to README.md for a complete installation and usage guide, if you have further questions. Please create a separate issue.
