### ISSUE TITLE
visulaization

### ISSUE THREAD

**Issue by usamaahme** [faizan1234567/Brain-Tumors-Segmentation#8]

**Comment by usamaahme** [comment]
How we can run show.py file to see the result e.g do we caan just runpython show.py so it will show us the result or we have to download the dataset and train the model?

**Comment by usamaahme** [comment]
where model weights is stored or if i have to change the files to see result ?

**Comment by faizan1234567** [comment]
@usamaahme I will update and test the visualization code. Model weights are not made public, because the method has not been published yet, and hence some details are private.
